import Head from 'next/head';
import { useState, useEffect } from 'react';
import styled from 'styled-components';

const StyledSection = styled.section`
  background-color: green;
  height: ${({ setHeight }) => setHeight ?? '20vh'};
`;

export default function Home() {
  const [reqHeight, setReqHeight] = useState(null);

  useEffect(() => {
    const viewportHeight = window.innerHeight;
    setReqHeight(viewportHeight - 270);
  }, [reqHeight]);

  return (
    <div>
      <Head>
        <title>Web Bulletin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <StyledSection setHeight={`${reqHeight}px`}>
        <p>Web Bulletin Blog Using Next and Strapi</p>
      </StyledSection>
    </div>
  );
}
